Repository KanbaraRyusei/Raosvior, pull requests merged in 2022-11, with the labels that each got.

#21 Playerの参照システムを作成
  Assets/Scripts/Manager/PlayerManager.cs
  Assets/Scripts/Manager/PlayerManager.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: HIGH, 機能 プログラム など :memo:, Todo

#22 PlayerPresenterの作成
  .editorconfig
  Assets/Scripts/Player/PlayerPresenter.cs
  Assets/Scripts/Player/PlayerPresenter.cs.meta
  Assets/Scripts/Player/PlayerView.cs
  Assets/Scripts/ScriptableObject/PlayerHand.cs
Labels: 完了 :ballot_box_with_check:, 機能 プログラム など :memo:, Todo

#24 Feature/character data
  Assets/Scripts/Character.meta
  Assets/Scripts/Character/ArcherData.cs
  Assets/Scripts/Character/ArcherData.cs.meta
  Assets/Scripts/Character/CharacterBase.cs
  Assets/Scripts/Character/CharacterBase.cs.meta
  Assets/Scripts/Character/GrapplerData.cs
  Assets/Scripts/Character/GrapplerData.cs.meta
  Assets/Scripts/Character/ShamanData.cs
  Assets/Scripts/Character/ShamanData.cs.meta
  Assets/Scripts/Character/knightData.cs
  Assets/Scripts/Character/knightData.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: 完了 :ballot_box_with_check:, 機能 プログラム など :memo:
